import { Header, Text } from '@samyos/shared/ui';
import { Metadata } from 'next';
import { useLocale } from 'next-intl';
import { getTranslator } from 'next-intl/server';
import { notFound } from 'next/navigation';

export const runtime = 'edge';

export const metadata: Metadata = {
  title: {
    template: '%s | SamyOs',
    default: 'Open Source | SamyOs',
  },
  description: 'Generated by create-nx-workspace',
};

export type LocaleParams = {
  locale: string;
};

export default async function Layout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: LocaleParams;
}) {
  const locale = useLocale();

  // Show a 404 error if the user requests an unknown locale
  if (params.locale !== locale) {
    notFound();
  }

  const t = await getTranslator(locale, 'Index');

  const items = [
    {
      label: t('header.nav.home'),
      locale,
      href: '/',
    },
    {
      label: t('header.nav.history'),
      locale,
      href: '/history',
    },
    {
      label: t('header.nav.learn'),
      locale,
      href: '/learn',
    },
  ];

  const Logo = <Text level="organism">SamyOs</Text>;

  return (
    <html lang={locale} className="h-screen">
      <body className="h-screen flex flex-col">
        <Header logo={Logo} items={items} />
        <main className="h-full">{children}</main>
      </body>
    </html>
  );
}
